spring.application.name=padmasiniAdmin_1
spring.data.mongodb.uri=mongodb+srv://swaminathan:swaminathan@subjects.sqqcggz.mongodb.net/?retryWrites=true&w=majority&appName=Subjects
server.port=80
server.port=${PORT:80}
# Allow files up to 50MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.profiles.active=test

# Redis (optional)
spring.session.store-type=redis
spring.redis.host=localhost
spring.redis.port=6379
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None
